### PR TITLE
ISSUE-32 - Check if job is active

### PR DESCRIPTION
**Pull request by rstalbow**

### CODE REVIEW

**Comment by cunla** [comment]
Do you mind writing a test for this? I am going to fix later today the tests that are failing...

**Review by cunla — APPROVED** [review]
Please squash and merge.
I will fix the failing tests later this week and publish a new version.
Thank you!

**Comment by rstalbow** [comment]
@cunla I dont see the option to Merge

**Comment by cunla** [comment]
> @cunla I dont see the option to Merge
It requires tests to pass. I'll merge it later this week.
Thanks again!
ן

**Pull request merged**
